config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'tasks#index'
  resources :tasks
  namespace :admin do
    resources :users
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labellings, dependent: :destroy
  has_many :tasks, through: :labellings
end

app/models/labelling.rb
class Labelling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :end_date, presence: true
  validates :status, presence: true

  enum status: {未着手:1, 着手中:2, 完了:3}
  enum priority: {高:1, 中:2, 低:3}
  # enum label_name: Label.pluck(:id, :name ).to_h

  scope :create_desc, -> { order(create_at: :desc) }
  scope :search_title, -> (params_title){
    where("title LIKE ?", "%#{params_title}%")}
  scope :search_status, ->(params_status){
    where(status: params_status)}
  scope :priority_asc, -> { order(priority: :asc) }

  belongs_to :user
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }
  before_destroy :admin_destroy_check
  before_update :admin_update_check
  validates :name,  presence: true, length: { maximum: 30 }
  validates :password, length: { minimum: 6 }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  has_secure_password

  has_many :tasks, dependent: :destroy

  private

  def admin_destroy_check
    if User.where(admin: true).count == 1 && self.admin == true
      throw(:abort)
    end
  end

  def admin_update_check
    if User.where(admin: true).count == 1 && self.admin == false
      throw(:abort)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :not_admin
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all.includes(:tasks)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "ユーザーを作成しました"
    else
      render :new
    end
  end

  def edit
  end

  def show
    @tasks = @user.tasks
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "ユーザーを編集しました"
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: "ユーザーを削除しました"
    else
      redirect_to admin_users_path
    end
  end

  private
  def not_admin
    unless current_user.admin?
      redirect_to tasks_path, notice: "管理者以外はアクセスできません"
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :login_required
  protect_from_forgery with: :exception
  include SessionsHelper

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    tasks = current_user.tasks
    @tasks = tasks.all.order(created_at: :desc)
    if params[:task].present?
      params_title = params[:task][:title]
      params_status = params[:task][:status]
      params_label = params[:task][:label_id]
      if (params_title && params_status).present?
        @tasks = @tasks.search_title(params_title).search_status(params_status)
      elsif params_title.present?
        @tasks = @tasks.search_title(params_title)
      elsif params_status.present?
        @tasks = @tasks.search_status(params_status)
      elsif params_label.present?
        @tasks = @tasks.joins(:labels).where(labels: { id: params_label })
      end

    elsif params[:sort_expired]
      @tasks = tasks.all.order(end_date: :desc)
    elsif params[:sort_priority]
      @tasks = tasks.all.order(priority: :asc)
    end
    @tasks = @tasks.page(params[:page]).per(5)
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.new(task_params)
    if @task.save
      redirect_to tasks_path, notice: "タスクを作成しました"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: "タスクを編集しました"
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice:"タスクを削除しました"
  end

  def confirm
    @task = Task.new(task_params)
    render :new if @task.invalid?
  end

  private

  def task_params
    params.require(:task).permit(
      :title,
      :content,
      :end_date,
      :status,
      :priority,
      { label_ids: [] }
    )
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    @user = User.new
    if logged_in?
      redirect_to tasks_path
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    unless current_user == @user
      redirect_to tasks_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_tasks_path
    elsif action_name == 'edit'
      task_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: [:admin,@user], local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :admin %>
  <%= f.check_box :admin %>

  <%= f.submit "編集" %>
<% end %>

<%= link_to t('tasks.back'), admin_users_path, class:"back btn-outline-primary btn-sm" %>

app/views/admin/users/index.html.erb
<h1>ユーザー管理画面</h1>
<p><%= notice %></p>

<%= link_to '新規ユーザー作成', new_admin_user_path %>


<table>
  <tr>
    <th>ユーザー名</th>
    <th>メールアドレス</th>
    <th>タスク数</th>
    <th>管理者</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.tasks.count %></td>
      <td><%= user.admin %></td>
      
      <td><%= link_to t('詳細'), admin_user_path(user.id) %></td>
      <td><%= link_to t('編集'), edit_admin_user_path(user.id) %></td>
      <td><%= link_to t('削除'), admin_user_path(user.id), method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/admin/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: [:admin,@user], local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create account" %>
<% end %>

<%= link_to "戻る", admin_users_path %>

app/views/admin/users/show.html.erb
<h1><%= @user.name %>タスク一覧</h1>

<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
    <th>終了期日</th>
    <th>状態</th>
    <th>優先度</th>
  </tr>

  <% @tasks.each do |task| %>
  <tr>
    <td><%= task.title %></td>
    <td><%= task.content %></td>
    <td><%= task.end_date %></td>
    <td><%= task.status %></td>
    <td><%= task.priority %></td>
    <td><%= link_to t('view.show'), task_path(task.id) %></td>
    <td><%= link_to t('view.edit'), edit_task_path(task.id) %></td>
    <td><%= link_to t('view.delete'), task_path(task.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
  <% end %>
</table>

<%= link_to "ユーザー管理画面", admin_users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manyou</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
      <meta name="viewport" content="width=device-width, initial-scale=1" />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="task_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="task_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="task_title">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date %>
  </div>
  <div class="task_title">
    <%= form.label :status %>
    <%= form.select :status, Task.statuses.keys.to_a,{} %>
  </div>

  <div class="task_title">
    <%= form.label :priority %>
    <%= form.select :priority, Task.priorities.keys.to_a,{} %>
  </div>

  <div class="task_title">
    <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
  </div>

  <%= form.submit %>
<% end %>


<%= link_to t('view.back'), tasks_path %>

app/views/tasks/confirm.html.erb
<h3>内容確認</h3>

<%= form_with(model: @task, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :status %>
  <%= form.hidden_field :end_date %>
  <%= form.hidden_field :priority %>

  <p>タイトル:<%= @task.title %></p>
  <p>本文:<%= @task.content %></p>
  <p>終了期限<%= @task.end_date %></p>
  <p>優先度<%= @task.priority %></p>
  <%= form.submit  "登録" %>

   <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>タスク 編集</h1>

<%= render 'form', task: @task %>

<%= link_to t('view.show'), @task %> |
<%= link_to t('view.back'), tasks_path %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<p><%= notice %></p>

<%= form_with(url: tasks_path, scope: :task, local: true, method: :get) do |form| %>
  <div class = "form-row">
    <span class = "form-group col-md-4">
      <%= form.text_field :title, placeholder:"タイトル検索", type: "text", class: "form-control",id: "inputcity" %>
    </span>
    <span class = "form-group col-md-2">
      <%= form.select :status, Task.statuses.keys.to_a, {include_blank: true}, id:"inputstate_status", class: "form-control" %>
    </span>
    <span class = "form-group col-md-2">
      <%= form.select :label_id, Label.pluck(:name, :id ).to_h, {include_blank: true}, id:"inputstate_label",class: "form-control" %>
    </span>
    <span>
      <%= form.submit "検索", class:"btn-secondary" %>
    </span>

    <button type="button" class="btn btn-outline-primary">
      <%= link_to "終了期限でソートする", tasks_path(sort_expired: "true") %>
    </button>
    <button type="button" class="btn btn-outline-primary">
      <%= link_to "優先度でソートする", tasks_path(sort_priority: "true") %>
    </button>
  </div>
<% end %>

<table>
  <tr>
    <th>ユーザー名</th>
    <th>タイトル</th>
    <th>内容</th>
    <th>終了期日</th>
    <th>状態</th>
    <th>優先度</th>
    <th>ラベル</th>
  </tr>


<% @tasks.each do |task| %>
    <tr class="task_row">
      <td><%= task.user.name %></td>
      <td><%= task.title %></td>
      <td><%= task.content %></td>
      <td><%= task.end_date %></td>
      <td><%= task.status %></td>
      <td><%= task.priority %></td>
      <td>
        <% task.labels.each do |label| %>
          <%= label.name %>
        <% end %>
      </td>
      <td><%= link_to t('view.show'), task_path(task.id) %></td>
      <td><%= link_to t('view.edit'), edit_task_path(task.id) %></td>
      <td><%= link_to t('view.delete'), task_path(task.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></td>
    </tr>
<% end %>
</table>

<br>

<%= link_to '新しいタスクを作成する', new_task_path %>

<%= paginate @tasks %>

app/views/tasks/new.html.erb
<h2>タスクを作成する</h2>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>タスク詳細</h1>
<p>タイトル: <%= @task.title %></p>
<p>内容: <%= @task.content %></p>
<p>終了期限: <%= @task.end_date %></p>
<p>ラベル：
  <% @task.labels.each do |label| %>
    <%= label.name %>
  <% end %>
</p>
<%= link_to t('view.back'), tasks_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<%= link_to 'Task一覧', tasks_path %>